name: 'Frist action'
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - run: npm run vue-tsc
